version: '3'

services:
  pg:
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
    volumes:
      - pg:/var/lib/postgresql/data

volumes:
  pg:
